stages:
- build
- test
build:
   stage: build
   script: 
   - fastlane build_for_testing
   artifacts:
      when: on_success
      paths:
      - build/**/*.xctest
test:
   stage: test
   script:
   - fastlane test