image: xcode/latest

stages:
  - test

xcode:
  # Replace with the version you need
  version: 13.X  # Update with your desired Xcode version

cache:
  paths:
    - cocoapods/DerivedData

before_script:
  - fastlane install_pods # Assuming you use CocoaPods

test:
  stage: test
  script:
    - xcodebuild clean build -workspace xcuitestproject.xcodeproj/ -scheme xcuitestproject -destination "platform=iOS Simulator,name=iPhone 13 Pro"
    - xctest -workspace xcuitestproject.xcodeproj/ -scheme xcuitestprojectUITests -destination "platform=iOS Simulator,name=iPhone 13 Pro"
  artifacts:
    paths:
      - DerivedData/Build/Products/Debug-iphonesimulator/your_app.app  # Replace with your app name
      - logs/**/*.log

