stages:
  - setup
  - test

variables:
  XCODE_SCHEME: "xcuitestprojectUITests"
  XCODE_DESTINATION: "platform=iOS Simulator,name=iPhone 15"

before_script:
  - xcode-select --install || true
  - sudo xcode-select --install || true
  - sudo xcode-select --reset

xcuitest_setup:
  stage: setup
  script:
    - xcode-select --install || true  # Try installing again
    - sudo xcode-select --install || true  # Try installing again with elevated privileges
    - sudo xcode-select --reset  # Reset the Xcode path
    - gem install bundler
    - bundle install

xcuitest:
  stage: test
  script:
    - xcodebuild test -project xcuitestproject.xcodeproj/ -scheme $XCODE_SCHEME -destination "$XCODE_DESTINATION"
  artifacts:
    paths:
      - "path/to/your/test/reports/*.xcresult"
