image: xcode/latest

stages:
  - test

variables:
  XCODE_SCHEME: "xcuitestprojectUITests"
  XCODE_DESTINATION: "platform=iOS Simulator,name=iPhone 15"

xcuitest:
  stage: test
  script:
    - xcodebuild test -project xcuitestproject.xcodeproj/ -scheme $XCODE_SCHEME -destination "$XCODE_DESTINATION"
  artifacts:
    paths:
      - "path/to/your/test/reports/*.xcresult"

