stages:
  - build

build_project:
  stage: build
  image: macos  # Use a macOS runner image
  script:
    - xcode-select --install  # Install Xcode command-line tools if not already installed
    - gem install xcpretty     
    - xcodebuild clean -project xcuitestproject.xcodeproj -scheme xcuitestprojectUITests | xcpretty
    - xcodebuild test -project xcuitestproject.xcodeproj -scheme xcuitestprojectUITests -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.5' | xcpretty -s