version: 2.1

jobs:
  build:
    macos:
      xcode: "15"  # Choose the desired Xcode version
    steps:
      - checkout

      # Install any necessary dependencies (if needed)
      # For example, you might install Homebrew packages or other dependencies here

      # # Build and run XCUITests
      # - run:
      #     name: Build and run XCUITests
      #     command: |
      #       xcodebuild -workspace YourWorkspace.xcworkspace -scheme YourScheme -destination 'platform=iOS Simulator,name=iPhone 13,OS=14.5' clean test

      # Build and run XCUITests
      - run:
          name: Build and run XCUITests
          command: |
            xcodebuild clean test -project xcuitestproject.xcodeproj -scheme xcuitestprojectUITests -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' | xcpretty -c
